### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by alex-angelov** [kyriakouandreas/RoboticArm#4]
1) There is no list of exact component models/manufacturers, or a sketch/CAD of the system design;
2) More information about expected latency between system components, bit rate, needed;
3) Power considerations - will the Pi (assuming you won't use a PSU) be able to supply enough power for the motors;
4) I don't understand what the BMP180 sensor has to do with a robotic arm;
5) RPi CPU benchmarks running parts of the project.
Good idea, but the github page looks a bit convoluted.
-Team 11

**Comment by sharraftel** [comment]
Hello,
1- there is a sketch with the stl files too in the "mech dis" folder.
3- if you look at the wiki you will find circuit diagrams, from them you will see that the rpi isnt powering the Motors ( that would be ridiculous)
4 we use that sensor to sense if the temp is too hot for the arm, it is 3d printed after all and we dont want to melt it, and we also use its pressure sensor so that the clamp dont put too much force into the objects it carries.
For the other issues we will put them on the github 
:)
Sharraf

**Comment by sharraftel** [comment]
hello, all the other issues had been solved, take a look at the wiki
cheers !!
