### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by tamercos** [kyriakouandreas/RoboticArm#6]
Not sure if I missed it, but installation instructions would be helpful! :)

Also, the repository is quite convoluted, but then again so is your project. If you can find a way to guide first time viewers effectively that would probably add a lot of value to your repository.

-team 16

**Comment by DevGero** [comment]
About the repository,
I am working on the README for the file that contains the latest version of the project code. But basically, the intention is to divide into simpler smaller tasks and avoid long main programs. For example, sensorthread.h and .cpp are in charge of the thread concerning the reading of the sensor but those not know who to access the hardware, this task is encapsulated as a class in bmp180.h and .cpp. That way any change in the GUI, the thread or the low-level access using wiringPi can be easily modified without going through extensive codes and also important can be reused by other person with different requirements. The same works for the i2cservocontroller class that can be accessed from the GUI and the physical buttons.

**Comment by DevGero** [comment]
On the WIKI there is a more detail description of the software and his layers. How the tasks are divided and the task of each one and how the objects and threads communicate and interact. This time should be less convoluted.
The installation guide for the software is in the README as well, since we have a version that is working properly. The same that we used for the YouTube video.

**Comment by sharraftel** [comment]
the instructions had been added 
cheers
